export type RootStackParamList = {
  MainTabs: undefined;
  Home: undefined;
  Stores: { storeTypeId?: number; vertical?: 'food' | 'groceries' };
  Products: { storeId: number; storeName: string; vertical?: 'food' | 'groceries' };
  Cart: undefined;
  Checkout: undefined;
  ProductDetails: { productId: number };
  Categories: undefined;
  ProductsByCategory: { categoryId: number; categoryName: string };
  UserLogin: undefined;
  SignupScreen: undefined;
  ForgotPassword: undefined;
  Services: undefined;
  ServiceDetail: { serviceId: number };
  Properties: undefined;
  PropertyDetail: { propertyId: number };
  Doctors: undefined;
  DoctorDetail: {
    doctorId: number;
    openSection?: 'overview' | 'location' | 'availability' | 'reviews';
  };
  BookAppointment: { doctorId: number };
  Accommodation: undefined;
  Wallet: undefined;
  BusinessDashboard: undefined;
  ComingSoon: undefined;
  Rides: undefined;
  RideTracking: { rideId: number };
  SendPackage: undefined;
  CarRental: undefined;
  Grocery: undefined;
  Food: undefined;
  Notifications: undefined;
};
