export type RootStackParamList = {
  MainTabs: undefined;
  Home: undefined;
  Stores: { storeTypeId?: number; vertical?: 'food' | 'groceries' };
  Products: { storeId: number; storeName: string; vertical?: 'food' | 'groceries' };
  Cart: undefined;
  Checkout: { storeId: number };
  ProductDetails: { productId: number };
  Categories: undefined;
  ProductsByCategory: { categoryId: number; categoryName: string };
  UserLogin: undefined;
  SignupScreen: undefined;
  CompleteProfile: undefined;
  ForgotPassword: undefined;
  Services: undefined;
  ServiceDetail: { serviceId: number };
  Properties: undefined;
  PropertyDetail: { propertyId: number };
  PropertyApplicationWizard: { propertyId: number };
  PropertyApplications: undefined;
  PropertyApplicationDetail: { applicationId: number };
  PropertyActiveRentals: undefined;
  PropertyDocumentsVault: undefined;
  StayBookings: undefined;
  StayBookingConfirm: { bookingId: number };
  Doctors: undefined;
  DoctorDetail: {
    doctorId: number;
    openSection?: 'overview' | 'location' | 'availability' | 'reviews';
  };
  BookAppointment: { doctorId: number };
  Accommodation: undefined;
  Wallet: undefined;
  BusinessDashboard: undefined;
  ComingSoon: undefined;
  Rides: undefined;
  RideTracking: { rideId: number };
  SendPackage: undefined;
  CarRental: undefined;
  CarRentalDetail: { vehicleId: number };
  Grocery:
    | {
        categorySlug?: string;
        section?: 'home' | 'categories' | 'favourites' | 'deals' | 'popular';
      }
    | undefined;
  Food: undefined;
  Notifications: undefined;
  Wishlist: undefined;
  UserProfile: undefined;
  SuccessScreen: undefined;
  CheckoutPage: { storeId?: number } | undefined;
  Delivery: undefined;
  CartPage: undefined;
  storeMenu: { storeId?: number } | undefined;
  FoodDetailsPage: { foodId?: number } | undefined;
  OrderHistory: undefined;
  HomeScreen: undefined;
  Profile: undefined;
  Activity: undefined;
  Support: undefined;
};
